//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FontsGeolabEduGe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Font
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Font()
        {
            this.Font_Design = new HashSet<Font_Design>();
            this.Font_Engineer = new HashSet<Font_Engineer>();
            this.Font_Mentor = new HashSet<Font_Mentor>();
            this.Font_Writing = new HashSet<Font_Writing>();
        }
    
        public int ID { get; set; }
        public string FontNamePre { get; set; }
        public string FontName { get; set; }
        public int FontTypeID { get; set; }
        public int CreateDateRangeID { get; set; }
        public string CreateDate { get; set; }
        public string DigitizationDate { get; set; }
        public string Ext { get; set; }
        public Nullable<bool> hasOneWidth { get; set; }
    
        public virtual CreateDateRange CreateDateRange { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Font_Design> Font_Design { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Font_Engineer> Font_Engineer { get; set; }
        public virtual FontType FontType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Font_Mentor> Font_Mentor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Font_Writing> Font_Writing { get; set; }
    }
}
