//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FontsGeolabEduGe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Font_Engineer
    {
        public int ID { get; set; }
        public int FontID { get; set; }
        public int EngineerID { get; set; }
    
        public virtual Engineer Engineer { get; set; }
        public virtual Font Font { get; set; }
    }
}
