//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FontsGeolabEduGe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FontsEntities : DbContext
    {
        public FontsEntities()
            : base("name=FontsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CreateDateRange> CreateDateRanges { get; set; }
        public virtual DbSet<Designer> Designers { get; set; }
        public virtual DbSet<Engineer> Engineers { get; set; }
        public virtual DbSet<Font> Fonts { get; set; }
        public virtual DbSet<Font_Design> Font_Design { get; set; }
        public virtual DbSet<Font_Engineer> Font_Engineer { get; set; }
        public virtual DbSet<Font_Mentor> Font_Mentor { get; set; }
        public virtual DbSet<Font_Writing> Font_Writing { get; set; }
        public virtual DbSet<FontType> FontTypes { get; set; }
        public virtual DbSet<Mentor> Mentors { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Writing> Writings { get; set; }
    }
}
